### ISSUE TITLE
Do a new release 

### ISSUE THREAD

**Issue by bmcage** [bmcage/odes#66]
I should do a new release, but with all doc changes an pypi changes, I'm not sure about all steps. It used to be:

For a Release: 

1. set in common.py version string and DEV=False, commit this.
2. In github, [draft a new release](https://github.com/bmcage/odes/releases) by clicking the appropriate button. Give correct version number, and hit release. This will upload the release for a DOI to [Zenado](https://zenodo.org) as draft
3. Go to uploads in [Zenado](https://zenodo.org), edit the uploaded new release, save and hit the publish button. This will generate a DOI.
4. update to pypi repo: `python setup.py sdist --formats=gztar register upload`
5. update version string to a higher number in common.py, and DEV=True, next copy the DOI badge of Zenado in the README.md, commit these two files.

Nothing changed to these instructions? I'd like to add these instructions to a dorelease.md in the project, so as to easily retrieve them later. 

For the release number 2.3.2 or 2.4.0 ? I'd take 2.3.2 as changes mostly doc related, not API.

Or do you have something in the pipeline you would want in the next release?

**Comment by aragilar** [comment]
There's nothing I was hoping to get in the next release (the multi-precision stuff can wait, and I haven't dug into numpy.distutils to work out how to make it work).

2.3.2 makes sense for the version.

The release instructions are fine (the docs on readthedocs and the api docs should auto-build, and use the tag for the release), but pypi has changed (the whole warehouse upgrade), so register doesn't do anything (I think the command actually fails now), and twine is supposed to be used rather than setup.py upload (setup.py upload still works though). I'll try to create a PR with a dorelease.md in the next few days.

**Comment by bmcage** [comment]
Ok, I'll wait then for that. Didn't follow pypi changes as I personally don't really use it. But many people do depend on it.

**Comment by bmcage** [comment]
released version 2.3.2, 87aeef43b8901ef61ea76b6ed0782196eecf0ab6
